FROM python:3.12-slim
RUN apt-get update && apt-get install -y bzip2 curl gcc
RUN curl -LO https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
RUN tar xzf go1.24.2.linux-amd64.tar.gz
RUN ln -s /go/bin/go /usr/local/bin
RUN python -m pip install --upgrade pip

COPY ./testdata/logs /tmp/logs
WORKDIR /code
COPY . .
COPY example.py /tmp
RUN python setup.py sdist
WORKDIR /tmp
# Check sdist
RUN python -m pip uninstall -y checksig
RUN python -m pip install /code/dist/checksig-0.1.0.tar.gz
RUN python example.py
