# Test docker file (used by CI)
FROM python:3.12-slim
RUN apt-get update && apt-get install -y bzip2 curl gcc
RUN curl -LO https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
RUN tar xzf go1.24.2.linux-amd64.tar.gz
RUN ln -s /go/bin/go /usr/local/bin
RUN python -m pip install --upgrade pip
COPY ./testdata/logs /tmp/logs
WORKDIR /code
COPY . .
RUN go build -buildmode=c-shared -o _checksig.so
RUN python py_session.py
