# Test docker file (used by CI)
FROM python:3.8-slim
RUN apt-get update && apt-get install -y bzip2 curl gcc
RUN curl -LO https://dl.google.com/go/go1.14.4.linux-amd64.tar.gz
RUN tar xzf go1.14.4.linux-amd64.tar.gz
RUN ln -s /go/bin/go /usr/local/bin
RUN python -m pip install --upgrade pip
COPY logs.tar.bz2 /tmp
RUN tar xjf /tmp/logs.tar.bz2 -C /tmp
WORKDIR /code
COPY . .
RUN go build -buildmode=c-shared -o _checksig.so
RUN python py_session.py
